#!/usr/bin/env node
/**
 * Per-agent local isolation for boop-watch (worktree + ports + DATA_DIR).
 *
 *   node scripts/agent-env.mjs up   <slug> [--base <ref>] [--seed [path]] [--no-install] [--link-modules]
 *   node scripts/agent-env.mjs down <slug> [--keep-branch]
 *   node scripts/agent-env.mjs ls
 *   node scripts/agent-env.mjs card <slug>
 *   node scripts/agent-env.mjs env  <slug>          # print shell exports (sourceable)
 *   node scripts/agent-env.mjs run  <slug> -- <cmd>  # run cmd in the worktree with slot env
 *
 * Each slug gets its own git worktree (`.agent-envs/<slug>/`), branch (`agent/<slug>`),
 * backend/Vite port pair, and `DATA_DIR`. Flow sink env is blanked (same idea as
 * preview-env) so parallel agents can't collide on qBittorrent / the media library.
 * Cap: MAX_AGENT_ENVS (default 5).
 *
 * Key = kebab-case slug (e.g. fix-subs). Pick something short and task-shaped;
 * it becomes the branch name, worktree dir, and registry key.
 */

import { execFileSync, spawnSync } from 'node:child_process'
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const MAX_AGENT_ENVS = Number(process.env.MAX_AGENT_ENVS || 5)
const DEFAULT_BASE = process.env.AGENT_ENV_BASE || 'origin/dev'
const BACKEND_PORT_BASE = Number(process.env.AGENT_ENV_BACKEND_PORT_BASE || 3101)
const VITE_PORT_BASE = Number(process.env.AGENT_ENV_VITE_PORT_BASE || 5174)
const SLUG_RE = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/
const BRANCH_PREFIX = 'agent/'

// Same sink keys preview-env blanks — parallel-safe. POSTHOG blanked so local
// agent traffic doesn't pollute the prod project. GitHub App left alone so agents
// can still open PRs from the worktree.
const BLANK_ENV = {
  QBIT_URL: '',
  QBIT_USERNAME: '',
  QBIT_PASSWORD: '',
  LIBRARY_DIR: '',
  POSTHOG_KEY: '',
}

function mainRepoRoot() {
  // Resolve via this script's parent so `up` from inside a worktree still
  // registers against the primary checkout's `.agent-envs/`.
  const probe = resolve(HERE, '..')
  const common = execFileSync('git', ['rev-parse', '--path-format=absolute', '--git-common-dir'], {
    cwd: probe,
    encoding: 'utf8',
  }).trim()
  return dirname(common)
}

const REPO = mainRepoRoot()
const ENVS_DIR = join(REPO, '.agent-envs')
const REGISTRY_PATH = join(ENVS_DIR, 'registry.json')

function git(args, { cwd = REPO, input, quiet } = {}) {
  return execFileSync('git', args, {
    cwd,
    input,
    encoding: 'utf8',
    stdio: input !== undefined ? ['pipe', 'pipe', quiet ? 'pipe' : 'inherit'] : ['ignore', 'pipe', quiet ? 'pipe' : 'inherit'],
  }).trim()
}

function loadRegistry() {
  if (!existsSync(REGISTRY_PATH)) return { version: 1, slots: {} }
  try {
    const raw = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'))
    return { version: 1, slots: raw.slots && typeof raw.slots === 'object' ? raw.slots : {} }
  } catch {
    return { version: 1, slots: {} }
  }
}

function saveRegistry(reg) {
  mkdirSync(ENVS_DIR, { recursive: true })
  writeFileSync(REGISTRY_PATH, `${JSON.stringify(reg, null, 2)}\n`)
}

function assertSlug(slug) {
  if (!slug || !SLUG_RE.test(slug) || slug.length > 40) {
    throw new Error(
      `invalid slug '${slug ?? ''}': use kebab-case (e.g. fix-subs), start with a letter, max 40 chars`,
    )
  }
}

function branchFor(slug) {
  return `${BRANCH_PREFIX}${slug}`
}

function worktreePath(slug) {
  return join(ENVS_DIR, slug)
}

function allocatePorts(slots, existing) {
  if (existing?.backendPort && existing?.vitePort) {
    return { backendPort: existing.backendPort, vitePort: existing.vitePort }
  }
  const usedBackend = new Set(Object.values(slots).map((s) => s.backendPort))
  const usedVite = new Set(Object.values(slots).map((s) => s.vitePort))
  let backendPort = BACKEND_PORT_BASE
  let vitePort = VITE_PORT_BASE
  while (usedBackend.has(backendPort) || usedVite.has(vitePort)) {
    backendPort += 1
    vitePort += 1
    if (backendPort > BACKEND_PORT_BASE + 100) {
      throw new Error('exhausted local agent port range; tear down an env with `agent-env down <slug>`')
    }
  }
  return { backendPort, vitePort }
}

function slotEnv(slot) {
  const dataDir = join(slot.path, 'data')
  return {
    ...BLANK_ENV,
    PORT: String(slot.backendPort),
    BACKEND_PORT: String(slot.backendPort),
    DATA_DIR: dataDir,
    AGENT_ENV_SLUG: slot.slug,
    AGENT_ENV_BRANCH: slot.branch,
    AGENT_ENV_ROOT: slot.path,
  }
}

function envFileContents(slot) {
  const env = slotEnv(slot)
  const lines = [
    `# Generated by scripts/agent-env.mjs — do not commit.`,
    `#   source .agent-env/env`,
    `#   npm run server:dev    # backend :${slot.backendPort}`,
    `#   npm run dev -- --port ${slot.vitePort} --strictPort`,
    '',
  ]
  for (const [k, v] of Object.entries(env)) {
    // Quote values; empty string is intentional for blanked sink keys.
    lines.push(`export ${k}=${JSON.stringify(v)}`)
  }
  lines.push(`export VITE_PORT=${JSON.stringify(String(slot.vitePort))}`)
  lines.push('')
  return lines.join('\n')
}

function cardContents(slot) {
  const baseUrl = `http://localhost:${slot.vitePort}`
  const apiUrl = `http://localhost:${slot.backendPort}`
  return [
    `# Agent env \`${slot.slug}\``,
    '',
    'Isolated worktree for one local agent. Work **only** in this directory so',
    'commits cannot mix with other agents.',
    '',
    '| | |',
    '|---|---|',
    `| **slug** | \`${slot.slug}\` |`,
    `| **branch** | \`${slot.branch}\` |`,
    `| **path** | \`${slot.path}\` |`,
    `| **base** | \`${slot.base}\` |`,
    `| **portal** | ${baseUrl} |`,
    `| **API /health** | ${apiUrl}/health |`,
    `| **DATA_DIR** | \`${join(slot.path, 'data')}\` |`,
    '',
    '## Start',
    '',
    '```bash',
    `cd ${slot.path}`,
    'source .agent-env/env',
    'npm run server:dev          # terminal 1',
    `npm run dev -- --port ${slot.vitePort} --strictPort   # terminal 2`,
    '```',
    '',
    'Or from the primary checkout:',
    '',
    '```bash',
    `node scripts/agent-env.mjs run ${slot.slug} -- npm run server:dev`,
    `node scripts/agent-env.mjs run ${slot.slug} -- npm run dev -- --port ${slot.vitePort} --strictPort`,
    '```',
    '',
    '## Tear down',
    '',
    '```bash',
    `node scripts/agent-env.mjs down ${slot.slug}`,
    '```',
    '',
    'Sink env (`QBIT_*`, `LIBRARY_DIR`) is blanked — dry-runs only, same as PR previews.',
    '',
  ].join('\n')
}

function writeSlotFiles(slot) {
  const dir = join(slot.path, '.agent-env')
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, 'env'), envFileContents(slot))
  writeFileSync(join(dir, 'card.md'), cardContents(slot))
  writeFileSync(
    join(dir, 'slot.json'),
    `${JSON.stringify({ ...slot, writtenAt: new Date().toISOString() }, null, 2)}\n`,
  )
}

function printCard(slot) {
  process.stdout.write(cardContents(slot))
}

function seedDataDir(slot, seedArg) {
  const dataDir = join(slot.path, 'data')
  mkdirSync(dataDir, { recursive: true })
  const dest = join(dataDir, 'series.sqlite')
  if (existsSync(dest)) return

  let src = null
  if (seedArg === true) {
    const candidates = [join(REPO, 'data', 'series.sqlite'), join(REPO, 'data', 'series.db')]
    src = candidates.find((p) => existsSync(p)) ?? null
    if (!src) {
      console.warn('(seed skipped: no data/series.sqlite in primary checkout — starting empty)')
      return
    }
  } else if (typeof seedArg === 'string') {
    src = resolve(seedArg)
    if (!existsSync(src)) throw new Error(`seed file not found: ${src}`)
  } else {
    return
  }

  copyFileSync(src, dest)
  // WAL/SHM sidecars if present (best-effort; safe to omit).
  for (const suf of ['-wal', '-shm']) {
    if (existsSync(src + suf)) copyFileSync(src + suf, dest + suf)
  }
  console.log(`Seeded DATA_DIR from ${src}`)
}

function installDeps(slot, { noInstall, linkModules }) {
  if (noInstall) {
    console.warn('(deps skipped: --no-install)')
    return
  }
  const nm = join(slot.path, 'node_modules')
  if (existsSync(nm)) return

  if (linkModules) {
    const primary = join(REPO, 'node_modules')
    if (!existsSync(primary)) {
      throw new Error('--link-modules requires node_modules in the primary checkout (run npm ci there first)')
    }
    symlinkSync(primary, nm)
    console.log(`Linked node_modules → ${primary}`)
    return
  }

  console.log('Installing deps in worktree (npm ci)…')
  const r = spawnSync('npm', ['ci', '--no-audit', '--no-fund'], {
    cwd: slot.path,
    stdio: 'inherit',
    env: process.env,
  })
  if (r.status !== 0) {
    console.warn('npm ci failed; falling back to npm install…')
    const r2 = spawnSync('npm', ['install', '--no-audit', '--no-fund'], {
      cwd: slot.path,
      stdio: 'inherit',
      env: process.env,
    })
    if (r2.status !== 0) throw new Error('npm install failed in agent worktree')
  }
}

function ensureBase(base) {
  // Fetch the ref's remote when it looks like origin/<branch>.
  const m = /^origin\/(.+)$/.exec(base)
  if (m) {
    try {
      git(['fetch', 'origin', m[1]], { quiet: true })
    } catch (err) {
      console.warn(`(fetch ${base} failed: ${String(err?.message || err).split('\n')[0]})`)
    }
  }
  try {
    git(['rev-parse', '--verify', `${base}^{commit}`], { quiet: true })
  } catch {
    throw new Error(`base ref not found: ${base}`)
  }
}

function up(slug, opts) {
  assertSlug(slug)
  const reg = loadRegistry()
  const branch = branchFor(slug)
  const path = worktreePath(slug)
  const base = opts.base || DEFAULT_BASE

  const existing = reg.slots[slug]
  if (existing && existsSync(existing.path || path)) {
    const slot = {
      ...existing,
      slug,
      branch: existing.branch || branch,
      path: existing.path || path,
      base: existing.base || base,
    }
    const ports = allocatePorts(reg.slots, slot)
    slot.backendPort = ports.backendPort
    slot.vitePort = ports.vitePort
    writeSlotFiles(slot)
    reg.slots[slug] = slot
    saveRegistry(reg)
    console.log(`Agent env '${slug}' already exists — refreshed card/env.\n`)
    printCard(slot)
    return
  }

  const active = Object.keys(reg.slots).filter((s) => existsSync(reg.slots[s].path || worktreePath(s)))
  if (!active.includes(slug) && active.length >= MAX_AGENT_ENVS) {
    throw new Error(
      `agent-env cap reached (${active.length}/${MAX_AGENT_ENVS}); tear one down or raise MAX_AGENT_ENVS`,
    )
  }

  ensureBase(base)
  mkdirSync(ENVS_DIR, { recursive: true })

  // Branch + worktree. Reuse a local branch if it already exists (resume).
  let branchExists = false
  try {
    git(['rev-parse', '--verify', `refs/heads/${branch}`], { quiet: true })
    branchExists = true
  } catch { /* new branch */ }

  if (existsSync(path)) {
    throw new Error(`worktree path already exists but is not registered: ${path} (remove it or \`down ${slug}\`)`)
  }

  if (branchExists) {
    console.log(`Creating worktree at ${path} (existing branch ${branch})`)
    git(['worktree', 'add', path, branch])
  } else {
    console.log(`Creating worktree at ${path} from ${base} → ${branch}`)
    git(['worktree', 'add', '-b', branch, path, base])
  }

  const ports = allocatePorts(reg.slots, existing)
  const slot = {
    slug,
    branch,
    path,
    base,
    backendPort: ports.backendPort,
    vitePort: ports.vitePort,
    createdAt: new Date().toISOString(),
  }

  mkdirSync(join(path, 'data'), { recursive: true })
  if (opts.seed !== false && opts.seed !== undefined) {
    seedDataDir(slot, opts.seed)
  } else if (opts.seed === undefined) {
    // Default: seed from primary data/ when present (no-op if missing).
    seedDataDir(slot, true)
  }

  installDeps(slot, opts)
  writeSlotFiles(slot)

  reg.slots[slug] = slot
  saveRegistry(reg)

  console.log(`\nAgent env ready: ${slug}`)
  printCard(slot)
}

function down(slug, { keepBranch } = {}) {
  assertSlug(slug)
  const reg = loadRegistry()
  const slot = reg.slots[slug]
  const path = slot?.path || worktreePath(slug)
  const branch = slot?.branch || branchFor(slug)

  console.log(`Tearing down agent env '${slug}'`)

  // Remove worktree if git knows about it (or the directory exists).
  try {
    git(['worktree', 'remove', '--force', path], { quiet: true })
  } catch {
    if (existsSync(path)) {
      rmSync(path, { recursive: true, force: true })
      try { git(['worktree', 'prune'], { quiet: true }) } catch { /* ok */ }
    }
  }

  if (!keepBranch) {
    try {
      git(['branch', '-D', branch], { quiet: true })
      console.log(`Deleted local branch ${branch}`)
    } catch {
      // Branch may already be gone or checked out elsewhere.
    }
  } else {
    console.log(`Kept branch ${branch} (--keep-branch)`)
  }

  delete reg.slots[slug]
  saveRegistry(reg)
  console.log(`Done.`)
}

function ls() {
  const reg = loadRegistry()
  const slugs = Object.keys(reg.slots).sort()
  if (slugs.length === 0) {
    console.log('No agent envs. Create one with: node scripts/agent-env.mjs up <slug>')
    return
  }
  for (const slug of slugs) {
    const s = reg.slots[slug]
    const alive = existsSync(s.path) ? 'ok' : 'MISSING'
    console.log(
      `${slug.padEnd(20)} ${alive.padEnd(8)} :${s.backendPort}/:${s.vitePort}  ${s.branch}  ${s.path}`,
    )
  }
}

function requireSlot(slug) {
  assertSlug(slug)
  const reg = loadRegistry()
  const slot = reg.slots[slug]
  if (!slot) throw new Error(`unknown agent env '${slug}' (try: node scripts/agent-env.mjs ls)`)
  if (!existsSync(slot.path)) {
    throw new Error(`agent env '${slug}' is registered but worktree missing at ${slot.path} — run down then up`)
  }
  return slot
}

function printEnv(slug) {
  const slot = requireSlot(slug)
  process.stdout.write(envFileContents(slot))
}

function runInSlot(slug, cmd) {
  const slot = requireSlot(slug)
  if (!cmd.length) throw new Error('run requires a command after --')
  const env = { ...process.env, ...slotEnv(slot), VITE_PORT: String(slot.vitePort) }
  const r = spawnSync(cmd[0], cmd.slice(1), {
    cwd: slot.path,
    stdio: 'inherit',
    env,
    shell: false,
  })
  process.exit(r.status ?? 1)
}

function usage(exit = 2) {
  console.error(`Usage:
  agent-env.mjs up   <slug> [--base <ref>] [--seed [path]] [--no-install] [--link-modules]
  agent-env.mjs down <slug> [--keep-branch]
  agent-env.mjs ls
  agent-env.mjs card <slug>
  agent-env.mjs env  <slug>
  agent-env.mjs run  <slug> -- <cmd> [args...]

Slug: kebab-case task id (e.g. fix-subs). Becomes branch agent/<slug> and
worktree .agent-envs/<slug>/. Cap: MAX_AGENT_ENVS=${MAX_AGENT_ENVS}.`)
  process.exit(exit)
}

function parseUpArgs(args) {
  const opts = { base: DEFAULT_BASE, seed: undefined, noInstall: false, linkModules: false }
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a === '--base') {
      opts.base = args[++i]
      if (!opts.base) throw new Error('--base requires a ref')
    } else if (a === '--seed') {
      const next = args[i + 1]
      if (next && !next.startsWith('-')) {
        opts.seed = next
        i++
      } else {
        opts.seed = true
      }
    } else if (a === '--no-seed') {
      opts.seed = false
    } else if (a === '--no-install') {
      opts.noInstall = true
    } else if (a === '--link-modules') {
      opts.linkModules = true
    } else {
      throw new Error(`unknown option: ${a}`)
    }
  }
  return opts
}

function main() {
  const [cmd, slug, ...rest] = process.argv.slice(2)
  if (!cmd || cmd === '-h' || cmd === '--help') usage(cmd ? 0 : 2)

  if (cmd === 'ls') {
    ls()
    return
  }
  if (cmd === 'up') {
    if (!slug) usage()
    up(slug, parseUpArgs(rest))
    return
  }
  if (cmd === 'down') {
    if (!slug) usage()
    down(slug, { keepBranch: rest.includes('--keep-branch') })
    return
  }
  if (cmd === 'card') {
    if (!slug) usage()
    printCard(requireSlot(slug))
    return
  }
  if (cmd === 'env') {
    if (!slug) usage()
    printEnv(slug)
    return
  }
  if (cmd === 'run') {
    if (!slug) usage()
    const dash = rest.indexOf('--')
    const cmdArgs = dash === -1 ? rest : rest.slice(dash + 1)
    runInSlot(slug, cmdArgs)
    return
  }
  console.error(`unknown command: ${cmd}`)
  usage()
}

try {
  main()
} catch (err) {
  console.error(String(err?.message || err))
  process.exit(1)
}
